language: cpp
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcv-dev libopencv-dev scilab 
script:
  - scilab -nw -e 'result = exec("tests.sce", "errcatch"); exit(result)'
  
